version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: company_zookeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: company_kafka
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1.test.local
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 501
  postgres:
    image: postgres:latest
    container_name: company_postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=company"
      - "POSTGRES_PASSWORD=company"
    ports:
            - "5432:5432"  # credentials (company:company)
